// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/reservation.repository_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/ferriyusra/movie-service/internal/model/entity"
	interfaces "github.com/ferriyusra/movie-service/internal/repository/interfaces"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	gorm "gorm.io/gorm"
)

// MockReservationRepository is a mock of ReservationRepository interface.
type MockReservationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationRepositoryMockRecorder
}

// MockReservationRepositoryMockRecorder is the mock recorder for MockReservationRepository.
type MockReservationRepositoryMockRecorder struct {
	mock *MockReservationRepository
}

// NewMockReservationRepository creates a new mock instance.
func NewMockReservationRepository(ctrl *gomock.Controller) *MockReservationRepository {
	mock := &MockReservationRepository{ctrl: ctrl}
	mock.recorder = &MockReservationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationRepository) EXPECT() *MockReservationRepositoryMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockReservationRepository) BeginTx(ctx context.Context) *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockReservationRepositoryMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockReservationRepository)(nil).BeginTx), ctx)
}

// Cancel mocks base method.
func (m *MockReservationRepository) Cancel(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockReservationRepositoryMockRecorder) Cancel(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockReservationRepository)(nil).Cancel), ctx, id)
}

// CreateWithTx mocks base method.
func (m *MockReservationRepository) CreateWithTx(ctx context.Context, tx *gorm.DB, reservation entity.ReservationEntity) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, reservation)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockReservationRepositoryMockRecorder) CreateWithTx(ctx, tx, reservation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockReservationRepository)(nil).CreateWithTx), ctx, tx, reservation)
}

// FindAll mocks base method.
func (m *MockReservationRepository) FindAll(ctx context.Context, filters interfaces.ReservationFilters) ([]entity.ReservationEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filters)
	ret0, _ := ret[0].([]entity.ReservationEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockReservationRepositoryMockRecorder) FindAll(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockReservationRepository)(nil).FindAll), ctx, filters)
}

// FindByID mocks base method.
func (m *MockReservationRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.ReservationEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.ReservationEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockReservationRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockReservationRepository)(nil).FindByID), ctx, id)
}

// FindByUserID mocks base method.
func (m *MockReservationRepository) FindByUserID(ctx context.Context, userID uuid.UUID, status string, page, limit int) ([]entity.ReservationEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, status, page, limit)
	ret0, _ := ret[0].([]entity.ReservationEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockReservationRepositoryMockRecorder) FindByUserID(ctx, userID, status, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockReservationRepository)(nil).FindByUserID), ctx, userID, status, page, limit)
}
