// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/reservation_seat.repository_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/ferriyusra/movie-service/internal/model/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	gorm "gorm.io/gorm"
)

// MockReservationSeatRepository is a mock of ReservationSeatRepository interface.
type MockReservationSeatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReservationSeatRepositoryMockRecorder
}

// MockReservationSeatRepositoryMockRecorder is the mock recorder for MockReservationSeatRepository.
type MockReservationSeatRepositoryMockRecorder struct {
	mock *MockReservationSeatRepository
}

// NewMockReservationSeatRepository creates a new mock instance.
func NewMockReservationSeatRepository(ctrl *gomock.Controller) *MockReservationSeatRepository {
	mock := &MockReservationSeatRepository{ctrl: ctrl}
	mock.recorder = &MockReservationSeatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservationSeatRepository) EXPECT() *MockReservationSeatRepositoryMockRecorder {
	return m.recorder
}

// CheckAvailabilityWithTx mocks base method.
func (m *MockReservationSeatRepository) CheckAvailabilityWithTx(ctx context.Context, tx *gorm.DB, showtimeID uuid.UUID, seatIDs []uuid.UUID) ([]entity.ReservationSeatEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAvailabilityWithTx", ctx, tx, showtimeID, seatIDs)
	ret0, _ := ret[0].([]entity.ReservationSeatEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAvailabilityWithTx indicates an expected call of CheckAvailabilityWithTx.
func (mr *MockReservationSeatRepositoryMockRecorder) CheckAvailabilityWithTx(ctx, tx, showtimeID, seatIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAvailabilityWithTx", reflect.TypeOf((*MockReservationSeatRepository)(nil).CheckAvailabilityWithTx), ctx, tx, showtimeID, seatIDs)
}

// CreateBatchWithTx mocks base method.
func (m *MockReservationSeatRepository) CreateBatchWithTx(ctx context.Context, tx *gorm.DB, seats []entity.ReservationSeatEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithTx", ctx, tx, seats)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithTx indicates an expected call of CreateBatchWithTx.
func (mr *MockReservationSeatRepositoryMockRecorder) CreateBatchWithTx(ctx, tx, seats interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithTx", reflect.TypeOf((*MockReservationSeatRepository)(nil).CreateBatchWithTx), ctx, tx, seats)
}

// FindByShowtimeID mocks base method.
func (m *MockReservationSeatRepository) FindByShowtimeID(ctx context.Context, showtimeID uuid.UUID) ([]entity.ReservationSeatEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShowtimeID", ctx, showtimeID)
	ret0, _ := ret[0].([]entity.ReservationSeatEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShowtimeID indicates an expected call of FindByShowtimeID.
func (mr *MockReservationSeatRepositoryMockRecorder) FindByShowtimeID(ctx, showtimeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShowtimeID", reflect.TypeOf((*MockReservationSeatRepository)(nil).FindByShowtimeID), ctx, showtimeID)
}
