// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/seat.repository_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/ferriyusra/movie-service/internal/model/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSeatRepository is a mock of SeatRepository interface.
type MockSeatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeatRepositoryMockRecorder
}

// MockSeatRepositoryMockRecorder is the mock recorder for MockSeatRepository.
type MockSeatRepositoryMockRecorder struct {
	mock *MockSeatRepository
}

// NewMockSeatRepository creates a new mock instance.
func NewMockSeatRepository(ctrl *gomock.Controller) *MockSeatRepository {
	mock := &MockSeatRepository{ctrl: ctrl}
	mock.recorder = &MockSeatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeatRepository) EXPECT() *MockSeatRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockSeatRepository) CreateBatch(ctx context.Context, seats []entity.SeatEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, seats)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockSeatRepositoryMockRecorder) CreateBatch(ctx, seats interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockSeatRepository)(nil).CreateBatch), ctx, seats)
}

// FindByTheaterID mocks base method.
func (m *MockSeatRepository) FindByTheaterID(ctx context.Context, theaterID uuid.UUID) ([]entity.SeatEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTheaterID", ctx, theaterID)
	ret0, _ := ret[0].([]entity.SeatEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTheaterID indicates an expected call of FindByTheaterID.
func (mr *MockSeatRepositoryMockRecorder) FindByTheaterID(ctx, theaterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTheaterID", reflect.TypeOf((*MockSeatRepository)(nil).FindByTheaterID), ctx, theaterID)
}
