// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/showtime.repository_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/ferriyusra/movie-service/internal/model/entity"
	interfaces "github.com/ferriyusra/movie-service/internal/repository/interfaces"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockShowtimeRepository is a mock of ShowtimeRepository interface.
type MockShowtimeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShowtimeRepositoryMockRecorder
}

// MockShowtimeRepositoryMockRecorder is the mock recorder for MockShowtimeRepository.
type MockShowtimeRepositoryMockRecorder struct {
	mock *MockShowtimeRepository
}

// NewMockShowtimeRepository creates a new mock instance.
func NewMockShowtimeRepository(ctrl *gomock.Controller) *MockShowtimeRepository {
	mock := &MockShowtimeRepository{ctrl: ctrl}
	mock.recorder = &MockShowtimeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShowtimeRepository) EXPECT() *MockShowtimeRepositoryMockRecorder {
	return m.recorder
}

// CheckConflict mocks base method.
func (m *MockShowtimeRepository) CheckConflict(ctx context.Context, theaterID uuid.UUID, startTime, endTime time.Time, excludeID *uuid.UUID) (*entity.ShowtimeEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConflict", ctx, theaterID, startTime, endTime, excludeID)
	ret0, _ := ret[0].(*entity.ShowtimeEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckConflict indicates an expected call of CheckConflict.
func (mr *MockShowtimeRepositoryMockRecorder) CheckConflict(ctx, theaterID, startTime, endTime, excludeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConflict", reflect.TypeOf((*MockShowtimeRepository)(nil).CheckConflict), ctx, theaterID, startTime, endTime, excludeID)
}

// Create mocks base method.
func (m *MockShowtimeRepository) Create(ctx context.Context, showtime entity.ShowtimeEntity) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, showtime)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockShowtimeRepositoryMockRecorder) Create(ctx, showtime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShowtimeRepository)(nil).Create), ctx, showtime)
}

// Delete mocks base method.
func (m *MockShowtimeRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShowtimeRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShowtimeRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockShowtimeRepository) FindAll(ctx context.Context, filters interfaces.ShowtimeFilters) ([]entity.ShowtimeEntity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filters)
	ret0, _ := ret[0].([]entity.ShowtimeEntity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockShowtimeRepositoryMockRecorder) FindAll(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockShowtimeRepository)(nil).FindAll), ctx, filters)
}

// FindByDate mocks base method.
func (m *MockShowtimeRepository) FindByDate(ctx context.Context, date time.Time) ([]entity.ShowtimeEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDate", ctx, date)
	ret0, _ := ret[0].([]entity.ShowtimeEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDate indicates an expected call of FindByDate.
func (mr *MockShowtimeRepositoryMockRecorder) FindByDate(ctx, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDate", reflect.TypeOf((*MockShowtimeRepository)(nil).FindByDate), ctx, date)
}

// FindByID mocks base method.
func (m *MockShowtimeRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.ShowtimeEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.ShowtimeEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockShowtimeRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockShowtimeRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockShowtimeRepository) Update(ctx context.Context, showtime entity.ShowtimeEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, showtime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShowtimeRepositoryMockRecorder) Update(ctx, showtime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShowtimeRepository)(nil).Update), ctx, showtime)
}
