// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/theater.repository_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/ferriyusra/movie-service/internal/model/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTheaterRepository is a mock of TheaterRepository interface.
type MockTheaterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTheaterRepositoryMockRecorder
}

// MockTheaterRepositoryMockRecorder is the mock recorder for MockTheaterRepository.
type MockTheaterRepositoryMockRecorder struct {
	mock *MockTheaterRepository
}

// NewMockTheaterRepository creates a new mock instance.
func NewMockTheaterRepository(ctrl *gomock.Controller) *MockTheaterRepository {
	mock := &MockTheaterRepository{ctrl: ctrl}
	mock.recorder = &MockTheaterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTheaterRepository) EXPECT() *MockTheaterRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTheaterRepository) Create(ctx context.Context, theater entity.TheaterEntity) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, theater)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTheaterRepositoryMockRecorder) Create(ctx, theater interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTheaterRepository)(nil).Create), ctx, theater)
}

// FindAll mocks base method.
func (m *MockTheaterRepository) FindAll(ctx context.Context) ([]entity.TheaterEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]entity.TheaterEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockTheaterRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockTheaterRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockTheaterRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.TheaterEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.TheaterEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTheaterRepositoryMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTheaterRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockTheaterRepository) Update(ctx context.Context, theater entity.TheaterEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, theater)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTheaterRepositoryMockRecorder) Update(ctx, theater interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTheaterRepository)(nil).Update), ctx, theater)
}
